##################
# Run from ~/mods as
# $> docker build -t dockerimage -f docker/Dockerfile.dev .
# Then use as
# $> docker run -ti -v ~/mods:/home dockerimage /bin/bash
##################
# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM ubuntu:18.04

LABEL maintainer='Stefan Dlugolinsky'
# MODS - Massive Online Data Streams

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends \
         git \
         curl \
         wget \
         python-setuptools \
         python-pip \
         python-wheel && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set the working directory
WORKDIR /home

# Install python packages listed in requirements.txt
RUN pip --no-cache-dir install -r /home/requirements.txt \
### (OPTIONAL!) If you want to use Jupyter, uncomment:
#        jupyter \
#        jupyterlab && \
#   python -m ipykernel.kernelspec \
###
    && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

### (OPTIONAL!) If you want to use Jupyter, uncomment: 
## Set up our notebook config.
#COPY docker/jupyter/jupyter_notebook_config.py /root/.jupyter/
#COPY docker/jupyter/run_jupyter.sh /
## For Jupyter terminal
#ENV SHELL /bin/bash
#
## REMINDER: Tensorflow Docker Images already EXPOSE ports 6006 and 8888
#EXPOSE 8888
###

