# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM ubuntu:18.04

LABEL maintainer='Stefan Dlugolinsky'
# MODS - Massive Online Data Streams

RUN apt-get update && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*


# Set the working directory
WORKDIR /home

# Script to run pylint
COPY mods/tests/run_pylint.sh /home

# Copy the current directory contents into the container at /home
ADD . /home

# Install pylint and python packages listed in requirements.txt
RUN python -m pip --no-cache-dir install pylint \
    -r /home/requirements.txt && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

